services:
  # Django app container
  app:
    build: .
    container_name: django_app
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "5001:8000"
    restart: always

volumes:
  static_volume:
  media_volume: