# Generated by Django 5.1.6 on 2025-05-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('avg_time', models.FloatField(default=0)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.DateTimeField(blank=True, null=True)),
                ('on_time', models.BooleanField(default=False)),
                ('in_full', models.BooleanField(default=False)),
                ('number_of_items', models.IntegerField()),
                ('ft_items', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('new_product', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.TextField()),
                ('cases', models.TextField()),
                ('number_cases', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('avg_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=60)),
                ('tpt', models.FloatField(default=0)),
                ('user', models.CharField(default='None', max_length=50)),
                ('user_type', models.CharField(default='None', max_length=50)),
                ('automatic', models.BooleanField(default=False)),
                ('rework', models.BooleanField(default=False)),
                ('case_index', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='api.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pattern', models.CharField(choices=[('Similar Value', 'Similar Value'), ('Similar Reference', 'Similar Reference'), ('Exact Match', 'Exact Match'), ('Similar Date', 'Similar Date'), ('Similar Vendor', 'Similar Vendor'), ('Multiple', 'Multiple')], max_length=50)),
                ('open', models.BooleanField(default=True)),
                ('group_id', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=6)),
                ('description', models.CharField(default='No description', max_length=250)),
                ('payment_method', models.CharField(default='Credit Card', max_length=50)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='GoodRecevied',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('product_code', models.CharField(max_length=100)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='api.contract')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='api.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('is_free_text', models.BooleanField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion1_order_items', to='api.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='case',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
    ]
