# Generated by Django 5.1.6 on 2025-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=60)),
                ('tpt', models.FloatField(default=0)),
                ('case_index', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.TextField()),
                ('cases', models.TextField()),
                ('number_cases', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('avg_time', models.FloatField(default=0)),
            ],
        ),
    ]
