# Generated by Django 5.1.6 on 2025-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_catalogitems_catalogitem_contract_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=255)),
                ('po_number', models.CharField(max_length=255)),
                ('invoice_item', models.PositiveIntegerField()),
                ('material_description', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('supplier_id', models.CharField(max_length=255)),
                ('invoice_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('database_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_match', models.BooleanField(default=False)),
                ('condition_qty_match', models.CharField(choices=[('equal', 'Equal'), ('higher', 'Higher'), ('lower', 'Lower')], max_length=20)),
                ('diff_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('database_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_match', models.BooleanField(default=False)),
                ('condition_price_match', models.CharField(choices=[('equal', 'Equal'), ('higher', 'Higher'), ('lower', 'Lower')], max_length=20)),
                ('diff_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_payment_terms', models.IntegerField()),
                ('database_payment_terms', models.IntegerField()),
                ('payment_terms_match', models.BooleanField(default=False)),
                ('condition_payment_terms', models.CharField(choices=[('equal', 'Equal'), ('higher', 'Higher'), ('lower', 'Lower')], max_length=20)),
                ('diff_payment_terms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'invoice_item'), name='unique_invoice_item')],
            },
        ),
    ]
