# Generated by Django 5.1.6 on 2025-05-27 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ocrinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinvoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrinvoiceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
