name: Deploy Backend to EC2 (Production Environment)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST_PROD }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and run script
        run: |
          set -e
          ssh ${{ secrets.EC2_USER_PROD }}@${{ secrets.EC2_HOST_PROD }} 'bash ~/deploy_backend.sh'
